name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        run: make build

      - name: Test image
        run: make test

      - name: Log into Dockerhub
        if: github.event_name != 'pull_request'
        # docker/login-action@v1.10.0
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: tekumara
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Dockerhub
        if: github.event_name != 'pull_request'
        run: make push
